name: "Terraform"

on:
  push: 
    branches: ["main"]
    paths: ["src/**"]
  workflow_dispatch:

jobs: 
  terraform:
    name: "Terraform Apply"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Configure AWS Credentials" 
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          
      - name: Checkout
        uses: actions/checkout@v4


      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip' # caching pip dependencies

      - name: Install Python dependencias
        working-directory: ./src/app
        run: pip install requests -t . 

      - name: Install Python dependencias
        working-directory: ./src/app
        run: pip install aws-lambda-powertools -t . 

      - name: Install Python dependencias
        working-directory: ./src/app
        run: pip install isNullOrEmpty -t . 
        
      - name: Terraform init
        working-directory: ./src
        run: terraform init 

      - name: Terraform Destroy 
        working-directory: ./src
        run: terraform destroy --auto-approve
        
      - name: Terraform Apply 
        working-directory: ./src
        run: terraform apply --auto-approve

